language: go

go:
  - 1.12.x

sudo: false


git:
  depth: 1


script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic
  - bash <(curl -s https://codecov.io/bash) -c -F unittests
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic -tags=integration -run=Integration
  - bash <(curl -s https://codecov.io/bash) -c -F integration
