language: go

go:
  - 1.12.x
  - tip

sudo: false


git:
  depth: 1


script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
